version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - ${HOME}/.config/article:/usr/src/app/.config/article # This ensures SQLite file persists
    environment:
      - NODE_ENV=development